### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by XhmikosR** [twbs/icons#5]
## Blocking

- [x] Use the upstream favicons
- [x] Don't use the master dist CSS. This can break any time
- [x] Move to Hugo (includes removing symlinks and timestamped CSS)
- [x] Add code snippet and examples from Bootstrap for usage section
- [x] Social icons
- [x] page description
- [x] social meta
- [x] Add license to the repo
- ~~See if we need to drop width/height. With these the icons aren't responsive?~~ Icons aren't responsive by design, but they can easily be modified for different dimensions by changing those attributes or custom CSS (like our docs). – @mdo
- [ ] Verify if we need `focusable="false"` and `role="img"` once and for all and adapt the svgo config to take this into consideration
- ~~Stop inlining all icons; this results in huge page size/DOM size~~ This is a feature I want to keep. – @mdo
- [x] Add testing
  - [x] HTML validation
  - [x] broken links
  - [x] CI

## Non-blocking

- [x] Add 404 page
- [ ] Move to Actions for automated releases on tag
- [ ] Move the hardcoded SVGs to includes
- [x] Do we need the search button? Seems useless since filtering happens when typing
- [x] Move list.js in the repo

**Comment by XhmikosR** [comment]
@mdo should we close this issue now?
